- name: configuring frontend component
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx server
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: starting and enabling service
    ansible.builtin.service: 
      name: nginx
      state: started
      enabled: yes
  
  - name: removing default content in html file
    ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

  - name: Downloading frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: extracting the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copying expense file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
    notify: restart nginx
  
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

      

      