- name: configuring mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql
    ansible.builtin.dnf:
     name: mysql-server
     state: present
  
  - name: enabling and starting mysql
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: setting up password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
